# -*- coding: utf-8 -*-
"""Copy of Intro_to_Python_I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nc_YdZ7OFm65hWYsBFVKEF81KeP8IPES

# **Lab 1 - Introduction to Python programming I**

Enter your code in the spaces provided.  Do not change any of the variable names or function names that are already provided for you.  In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.
"""

# Do not edit this cell.

LabID="Lab1"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

"""**Enter your name, section number, and BYU NetID**"""

# Enter your first and last names in between the quotation marks.

first_name="Dallin"

last_name="Henderson"

# Enter your Math 215 section number in between the quotation marks. 

section_number="1"  

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER!

BYUNetID="henderda"

"""**Problem 1**"""

my_first_var=(118+(11*2))/(9-2)  # Replace the value of 0 with the required expression from Problem 1.

"""**Problem 2**"""

def arithmetic2(i):
  return 3*(i+2)-5

arithmetic2(3)
arithmetic2(-10)

"""**Problem 3**"""

def triple(y):
  return 3*y

triple(10)

def avg(x,y):
  return (x+y)/2

avg(5,25)

def combine(x,y):
  var=avg(x,triple(y))
  return var

combine(6,5)

"""**Problem 4**"""

def first(c):
  var = c[0]
  return var

def first_last(c):
  f=c[0]
  l=c[-1]
  return f,l

list_var=[1,2,3,4,5]
first_last(list_var)

def middle(c):
  d=c.copy()
  return d[1:-1]

list_var=[1,2,3,4,5]
middle(list_var)

"""**Problem 5**"""

def swap(c):
  original_list=c.copy() # This creates a copy of the list c, which is called original_list.  Your function should work with this list instead of the list c which is passed to the function.
  f=original_list[0]
  l=original_list[-1]
  original_list[-1]=f
  original_list[0]=l
  return original_list

swap([0,1,2,3,4,5])

"""**Problem 6**"""

def absolute_value(x):
  if x < 0:
    x=x*(-1)
  return x

absolute_value(-10)

"""**Problem 7**"""

def indicator(lower,upper,n):
  if (lower <= n) and (n <= upper):
    val = 1
  else:
    val = 0
  return val

indicator(-3,9,8)

"""**Problem 8**"""

def trunc_max(x,y):
  if (x > 0) or (y > 0):
    if x>y:
      val = x
    else:
      val = y
  else:
    val = 0
  return val

trunc_max(-173,-21)

"""**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to http://www.math.byu.edu:30000 for grading.
"""